<!DOCTYPE html>
<html lang="en">
<head>
<title>JavaScript Errors - Throw and Try to Catch</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0"
charset="UTF-8">
<meta name="description" content="Free Web tutorials">
<meta name="keywords" content="HTML, CSS, SQL">
<meta name="author" content="John Doe">
<link rel="stylesheet"
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet"
href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet"
href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link type="text/css" rel="stylesheet"
href="../../css/17.09-JavaScript Errors - Throw and Try to Catch.css" />
<style></style>
</head>

<body>
<h1 class="chapters">JavaScript Errors - Throw and Try to Catch</h1>
<p>The <b>try</b> statement lets you test a block of code for errors. The 
    <b>catch</b> statement lets you handle the error. The <b>throw</b> 
    statement lets you create custom errors. The <b>finally</b> statement 
    lets you execute code, after try and catch, regardless of the result.</p>
<p>When executing JavaScript code, different errors can occur. Errors can be 
    coding errors made by the programmer, errors due to wrong input, and 
    other unforeseeable things.</p>
<p id="demo1"></p>

<script>
    try {
        adddlert("Welcome guest!");
    }
    catch (err) {
        document.getElementById("demo1").innerHTML = err.message;
    }
</script>

<div class="note">JavaScript catches <b>adddlert</b> as an error, and 
    executes the catch code to handle it.</div>

<h2>JavaScript try and catch</h2>
<p>The <b>try</b> statement allows you to define a block of code to be tested 
    for errors while it is being executed. The <b>catch</b> statement allows 
    you to define a block of code to be executed, if an error occurs in the 
    try block. The JavaScript statements <b>try</b> and <b>catch</b> come in 
    pairs:</p>

<div class="bb">try {<br>
<em>Block of code to try</em><br>
}<br>
catch(err) {<br>
<em>Block of code to handle errors</em><br>
}</div>

<h2>JavaScript Throws Errors</h2>
<p>When an error occurs, JavaScript will normally stop and generate an error 
    message. The technical term for this is: JavaScript will <b>throw an 
    exception (throw an error)</b>.</p>

<div class="note">JavaScript will actually create an <b>Error object</b> with 
two properties: <b>name</b> and <b>message</b>.</div>

<h2>The throw Statement</h2>
<p>The <b>throw</b> statement allows you to create a custom error. 
    Technically you can <b>throw an exception (throw an error)</b>. The 
    exception can be a JavaScript String, a Number, a Boolean or an Object:</p>

<div class="bb">throw "Too big"; // throw a text<br>
throw 500; // throw a number</div>

<p>If you use <b>throw</b> together with <b>try</b> and <b>catch</b>, you can 
    control program flow and generate custom error messages.</p>

<h2>Input Validation Example</h2>
<p>This example examines input. If the value is wrong, an exception (err) is 
    thrown. The exception (err) is caught by the catch statement and a custom 
    error message is displayed. Please input a number between 5 and 10:</p>

<input id="demo2" type="text">
<button type="button" onclick="myFunction2()">Test Input</button>
<p id="p02"></p>

<script>
    function myFunction2() {
        var message, x;
        message = document.getElementById("p02");
        message.innerHTML = "";
        x = document.getElementById("demo2").value;
        try {
            if (x == "") throw "empty";
            if (isNaN(x)) throw "not a number";
            x = Number(x);
            if (x < 5) throw "too low";
            if (x > 10) throw "too high";
        }
        catch (err) {
            message.innerHTML = "Input is " + err;
        }
    }
</script>

<h2>HTML Validation</h2>
<p>The code above is just an example. Modern browsers will often use a 
    combination of JavaScript and built-in HTML validation, using predefined 
    validation rules defined in HTML attributes:</p>

<div class="bb">&ltinput id="demo" type="number" min="5" max="10" step="1"&gt
</div>

<h2>The finally Statement</h2>
<p>The <b>finally</b> statement lets you execute code, after try and catch, 
    regardless of the result:</p>

<div class="bb">try {<br>
<em>Block of code to try</em><br>
}<br>
catch(err) {<br>
<em>Block of code to handle errors</em><br>
}<br>
finally {<br>
<em>Block of code to be executed regardless of the try / catch result</em><br>
}</div>

<p>Please input a number between 5 and 10:</p>

<input id="demo3" type="text">
<button type="button" onclick="myFunction3()">Test Input</button>

<p id="p03"></p>

<script>
    function myFunction3() {
        var message, x;
        message = document.getElementById("p03");
        message.innerHTML = "";
        x = document.getElementById("demo3").value;
        try {
            if (x == "") throw "is empty";
            if (isNaN(x)) throw "is not a number";
            x = Number(x);
            if (x > 10) throw "is too high";
            if (x < 5) throw "is too low";
        }
        catch (err) {
            message.innerHTML = "Input " + err;
        }
        finally {
            document.getElementById("demo3").value = "";
        }
    }
</script>

<h2>The Error Object</h2>
<p>JavaScript has a built in error object that provides error information 
    when an error occurs. The error object provides two useful properties: 
    name and message.</p>

<h2>Error Object Properties</h2>
<table class="properties">
    <tr>
        <th>Property</th>
        <th>Description</th>
    </tr>
    <tr>
        <td>name</td>
        <td>Sets or returns an error name</td>
    </tr>
    <tr>
        <td>message</td>
        <td>Sets or returns an error message (a string)</td>
    </tr>
</table>

<h2>Error Name Values</h2>
<p>Six different values can be returned by the error name property:</p>
<table class="properties">
    <tr>
        <th>Error Name</th>
        <th>Description</th>
    </tr>
    <tr>
        <td>EvalError</td>
        <td>An error has occurred in the eval() function</td>
    </tr>
    <tr>
        <td>RangeError</td>
        <td>A number "out of range" has occurred</td>
    </tr>
    <tr>
        <td>ReferenceError</td>
        <td>An illegal reference has occurred</td>
    </tr>
    <tr>
        <td>SyntaxError</td>
        <td>A syntax error has occurred</td>
    </tr>
    <tr>
        <td>TypeError</td>
        <td>A type error has occurred</td>
    </tr>
    <tr>
        <td>URIError</td>
        <td>An error in encodeURI() has occurred</td>
    </tr>
</table>

<p>The six different values are described below.</p>

<h2>Eval Error</h2>
<p>An <b>EvalError</b> indicates an error in the eval() function.</p>

<div class="warning">Newer versions of JavaScript do not throw any EvalError. 
    Use SyntaxError instead.</div>

<h2>Range Error</h2>
<p>A <b>RangeError</b> is thrown if you use a number that is outside the 
    range of legal values. For example: You cannot set the number of 
    significant digits of a number to 500.</p>

<p id="demo4">

    <script>
        var num = 1;
        try {
            num.toPrecision(500);
        }
        catch (err) {
            document.getElementById("demo4").innerHTML = err.name;
        }
    </script>

<h2>Reference Error</h2>
<p>A <b>ReferenceError</b> is thrown if you use (reference) a variable that 
    has not been declared:</p>
<p id="demo5"></p>

<script>
    var x;
    try {
        x = y + 1;
    }
    catch (err) {
        document.getElementById("demo5").innerHTML = err.name;
    }
</script>

<h2>Syntax Error</h2>
<p>A <b>SyntaxError</b> is thrown if you try to evaluate code with a syntax 
    error.</p>
<p id="demo6"></p>

<script>
    try {
        eval("alert('Hello)");
    }
    catch (err) {
        document.getElementById("demo6").innerHTML = err.name;
    }
</script>

<h2>Type Error</h2>
<p>A <b>TypeError</b> is thrown if you use a value that is outside the range 
    of expected types:</p>
<p id="demo7"></p>

<script>
    var num = 1;
    try {
        num.toUpperCase();
    }
    catch (err) {
        document.getElementById("demo7").innerHTML = err.name;
    }
</script>

<h2>URI (Uniform Resource Identifier) Error</h2>
<p>A <b>URIError</b> is thrown if you use illegal characters in a URI 
    function:</p>
<p id="demo8"></p>

<script>
    try {
        decodeURI("%%%");
    }
    catch (err) {
        document.getElementById("demo8").innerHTML = err.name;
    }
</script>

<h2>Non-Standard Error Object Properties</h2>

<div class="warning">Mozilla and Microsoft defines some non-standard error 
    object properties:<br>

fileName (Mozilla)<br>
lineNumber (Mozilla)<br>
columnNumber (Mozilla)<br>
stack (Mozilla)<br>
description (Microsoft)<br>
number (Microsoft)<br>

Do not use these properties in public web sites. They will not work in all browsers.</div>




</body>
</html>